// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpceyonfjfjaogwkyrhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwY2V5b25mamZqYW9nd2t5cmhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyMTIzOTAsImV4cCI6MjA4ODc4ODM5MH0.kwKuzt1HTvDJOo2Apq5vJ_30CKiJVPob3JIS33d-KaM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});